const keyboardButtons = [
  [
    {
      name: 'Backquote',
      lang: { en: '`', ru: 'ё' },
      isFunctional: false,
      size: 'm',
    },
    {
      name: 'Digit1',
      lang: { en: '1', ru: '1' },
      isFunctional: false,
      size: 'm',
    },
    {
      name: 'Digit2',
      lang: { en: '2', ru: '2' },
      isFunctional: false,
      size: 'm',
    },
    {
      name: 'Digit3',
      lang: { en: '3', ru: '3' },
      isFunctional: false,
      size: 'm',
    },
    {
      name: 'Digit4',
      lang: { en: '4', ru: '4' },
      isFunctional: false,
      size: 'm',
    },
    {
      name: 'Digit5',
      lang: { en: '5', ru: '5' },
      isFunctional: false,
      size: 'm',
    },
    {
      name: 'Digit6',
      lang: { en: '6', ru: '6' },
      isFunctional: false,
      size: 'm',
    },
    {
      name: 'Digit7',
      lang: { en: '7', ru: '7' },
      isFunctional: false,
      size: 'm',
    },
    {
      name: 'Digit8',
      lang: { en: '8', ru: '8' },
      isFunctional: false,
      size: 'm',
    },
    {
      name: 'Digit9',
      lang: { en: '9', ru: '9' },
      isFunctional: false,
      size: 'm',
    },
    {
      name: 'Digit0',
      lang: { en: '0', ru: '0' },
      isFunctional: false,
      size: 'm',
    },
    {
      name: 'Minus',
      lang: { en: '-', ru: '-' },
      isFunctional: false,
      size: 'm',
    },
    {
      name: 'Equal',
      lang: { en: '=', ru: '=' },
      isFunctional: false,
      size: 'm',
    },
    {
      name: 'Backspace',
      lang: { en: 'delete', ru: 'delete' },
      isFunctional: true,
      size: 'l',
    },
  ],
  [
    {
      name: 'Tab',
      lang: { en: 'tab', ru: 'tab' },
      isFunctional: true,
      size: 'l',
    },
    {
      name: 'KeyQ',
      lang: { en: 'q', ru: 'й' },
      isFunctional: false,
      size: 's',
    },
    {
      name: 'KeyW',
      lang: { en: 'w', ru: 'ц' },
      isFunctional: false,
      size: 's',
    },
    {
      name: 'KeyE',
      lang: { en: 'e', ru: 'у' },
      isFunctional: false,
      size: 's',
    },
    {
      name: 'KeyR',
      lang: { en: 'r', ru: 'к' },
      isFunctional: false,
      size: 's',
    },
    {
      name: 'KeyT',
      lang: { en: 't', ru: 'е' },
      isFunctional: false,
      size: 's',
    },
    {
      name: 'KeyY',
      lang: { en: 'y', ru: 'н' },
      isFunctional: false,
      size: 's',
    },
    {
      name: 'KeyU',
      lang: { en: 'u', ru: 'г' },
      isFunctional: false,
      size: 's',
    },
    {
      name: 'KeyI',
      lang: { en: 'i', ru: 'ш' },
      isFunctional: false,
      size: 's',
    },
    {
      name: 'KeyO',
      lang: { en: 'o', ru: 'щ' },
      isFunctional: false,
      size: 's',
    },
    {
      name: 'KeyP',
      lang: { en: 'p', ru: 'з' },
      isFunctional: false,
      size: 's',
    },
    {
      name: 'BracketLeft',
      lang: { en: '[', ru: 'х' },
      isFunctional: false,
      size: 's',
    },
    {
      name: 'BracketRight',
      lang: { en: ']', ru: 'ъ' },
      isFunctional: false,
      size: 's',
    },
    {
      name: 'Backslash',
      lang: { en: '\\', ru: '\\' },
      isFunctional: false,
      size: 's',
    },
  ],
];

export default keyboardButtons;
